// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjq6ELyO-mIpRPy5z-kfaefDqpD-fWnnc',
    appId: '1:371483128957:web:dff4339f0827be8489ed14',
    messagingSenderId: '371483128957',
    projectId: 'flutter-fasum-app',
    authDomain: 'flutter-fasum-app.firebaseapp.com',
    storageBucket: 'flutter-fasum-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvG0780Bv5cv9i_VeKg2cDdxEfTEkIw-M',
    appId: '1:371483128957:android:35cc01474e2cd50289ed14',
    messagingSenderId: '371483128957',
    projectId: 'flutter-fasum-app',
    storageBucket: 'flutter-fasum-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR9bG_sj58zZqdO0lib1B2Xs_SFZ2Z8ZU',
    appId: '1:371483128957:ios:b87e8aee70089e0c89ed14',
    messagingSenderId: '371483128957',
    projectId: 'flutter-fasum-app',
    storageBucket: 'flutter-fasum-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR9bG_sj58zZqdO0lib1B2Xs_SFZ2Z8ZU',
    appId: '1:371483128957:ios:b87e8aee70089e0c89ed14',
    messagingSenderId: '371483128957',
    projectId: 'flutter-fasum-app',
    storageBucket: 'flutter-fasum-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjq6ELyO-mIpRPy5z-kfaefDqpD-fWnnc',
    appId: '1:371483128957:web:99d0f73f53d59da489ed14',
    messagingSenderId: '371483128957',
    projectId: 'flutter-fasum-app',
    authDomain: 'flutter-fasum-app.firebaseapp.com',
    storageBucket: 'flutter-fasum-app.firebasestorage.app',
  );
}
