// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8lPJB4LtyNUzHTmbc5mK5hjXYfY5WLM',
    appId: '1:784801906347:web:344eb6d78063877b9f01ee',
    messagingSenderId: '784801906347',
    projectId: 'prjpab2-si61-2327240137',
    authDomain: 'prjpab2-si61-2327240137.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240137.firebasestorage.app',
    measurementId: 'G-9HMP44VS7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcXEsqIRahziwcT536tgULBE6_aQ5MAE',
    appId: '1:784801906347:android:fd55dab7deefb2919f01ee',
    messagingSenderId: '784801906347',
    projectId: 'prjpab2-si61-2327240137',
    storageBucket: 'prjpab2-si61-2327240137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxs13XSoC2BDbc-7Zwsb_yTe23ZHg_bs4',
    appId: '1:784801906347:ios:056f8ea2ca7a74b19f01ee',
    messagingSenderId: '784801906347',
    projectId: 'prjpab2-si61-2327240137',
    storageBucket: 'prjpab2-si61-2327240137.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxs13XSoC2BDbc-7Zwsb_yTe23ZHg_bs4',
    appId: '1:784801906347:ios:056f8ea2ca7a74b19f01ee',
    messagingSenderId: '784801906347',
    projectId: 'prjpab2-si61-2327240137',
    storageBucket: 'prjpab2-si61-2327240137.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ8lPJB4LtyNUzHTmbc5mK5hjXYfY5WLM',
    appId: '1:784801906347:web:0ba417f3ecbd56809f01ee',
    messagingSenderId: '784801906347',
    projectId: 'prjpab2-si61-2327240137',
    authDomain: 'prjpab2-si61-2327240137.firebaseapp.com',
    storageBucket: 'prjpab2-si61-2327240137.firebasestorage.app',
    measurementId: 'G-9V6B2EGSLF',
  );

}